### ISSUE TITLE
一个潜在的兼容性Bug

### ISSUE THREAD

**Issue by tao2years** [upupming/HITMers#2]
在项目中，发现没有使用wx.getSystemInfo这个API去获取使用机型的系统信息。
然后通过windowWidth，windowHeight和safeArea来调整小程序的布局设置。

没有通过wx.getSystemInfo的适配，在部分机型上可能会出现一些样式问题。

**Comment by tao2years** [comment]
您好关闭issue是已经确认了问题吗还是有其他兼容样式的方法。比如iPhoneX     @@@@底部有一部分安全区域（小黑条遮挡）

> 在项目中，发现没有使用wx.getSystemInfo这个API去获取使用机型的系统信息。
> 然后通过windowWidth，windowHeight和safeArea来调整小程序的布局设置。
> 
> 没有通过wx.getSystemInfo的适配，在部分机型上可能会出现一些样式问题。

**Comment by upupming** [comment]
@598807302 项目确实可能有这种问题，但是已经很久没有开发了，所以可能不会去适配这个问题

**Comment by tao2years** [comment]
好的感谢。在iPhoneX系列需要适配下巴小黑条，刘海屏可能需要适配顶部导航栏。

**Comment by upupming** [comment]
> 好的感谢。在iPhoneX系列需要适配下巴小黑条，刘海屏可能需要适配顶部导航栏。

是的，这个可以看苹果的官方文档～实现起来应该难度不大
